function StructType = initStruct3(type)
%% Constants
TYPE_FILE = 'FILE';
TYPE_IT = 'IT';
TYPE_IV = 'IV';
TYPE_CAP = 'CAP';
TYPE_STEP = 'STEP';

%% Variables
choice = '';

%% Function
if contains(type,TYPE_FILE,'IgnoreCase',true)
    choice = TYPE_FILE;
    choiceDisp = 'file';
elseif contains(type,TYPE_IT,'IgnoreCase',true)
    choice = TYPE_IT;
    choiceDisp = 'current vs. time';
elseif contains(type,TYPE_IV,'IgnoreCase',true)
    choice = TYPE_IV;
    choiceDisp = 'current vs. voltage';
elseif contains(type,TYPE_CAP,'IgnoreCase',true)
    choice = TYPE_CAP;
    choiceDisp = 'capacitance';
elseif contains(type,TYPE_STEP,'IgnoreCase',true)
    choice = TYPE_STEP;
    choiceDisp = 'step voltage';
end
fprintf('Initializing %s database...',choiceDisp);

Channels = struct(...	% initialize structure
    'Number',[],...       % type
    'Name',[]);         % ID

Experiment = struct(...	% initialize structure
    'Type',[],...       % type
    'ID',[],...         % ID
    'Channels',Channels,...
    'Parameters',[],... % parameters
    'Quit',[]);

Processing = struct(...
    'Step',[],...
    'Buffer',[],...
    'NumberOfSamples',[],...
    'Values',[]);

Buffer = struct(...
    'Points',[],...
    'SamplingRate',[]);

Speed = struct(...
    'Mode',[],...
    'NPLC',[],...
    'SamplingRate',[],...
    'SamplingPeriod',[]);

Settings = struct(...
    'Display',[],...
    'PowerLine',[],...
    'SourceDelay',[],...
    'CurrentRange',[],...
    'Speed',Speed,...
    'AutoZero',[],...
    'GroundConnectMode',[],...
    'RelativeOffset',[],...
    'Buffer',Buffer);

Instrument = struct(...
    'Resource',[],...
    'Object',[],...
    'Processing',Processing,...
    'Settings',Settings);

Exclude = struct(...
    'Index',[],...
    'Time',[],...
    'Current',[]);

Statistics = struct(...
    'Buffer',[],...
    'Mean',[],...
    'StandardDeviations',[],...
    'Slope',[],...
    'Intercept',[],...
    'Regression',[],...
    'Exclude',Exclude);

StepData = struct(...
    'Step',[],...
    'VoltageBias',[],...
    'Data',[],...
    'Statistics',Statistics,...
    'Completed',[]);

Failure = struct(...
    'Found',[],...
    'Step',[]);

switch choice
    case TYPE_FILE
        StructType = struct(...	% initialize structure
            'Notebook',[],...           % notebook
            'Subject',[],...            % subject
            'Instrument',Instrument,... % instrument
            'Experiment',Experiment,... % experiment
            'Data',[],...             % data
            'StepData',StepData,...
            'Path',[],...               % path
            'DateTimeCreated',[],...    % date and time created
            'DateTimeModified',[],...   % date and time completed
            'RecordedBy',[],...         % name
            'Email',[]);                % email

    case TYPE_IT
        StructType = struct(...	% initialize structure
            'Channel',[],...    % channel name
            'Voltage',[],...    % voltage bias
            'Time',[],...       % time
            'Current',[],...    % leakage curent
            'Statistics',Statistics,...
            'DateTimeStart',[],...  % date and time started
            'DateTimeEnd',[]);    	% date and time ended

    case TYPE_IV
        StructType = struct(...	% initialize structure
            'Channel',[],...    % channel name
            'Voltage',[],...    % voltage bias
            'Current',[],...    % leakage curent
            'StepData',[],...
            'Resistance',[],...
            'Regression',[],...
            'DateTimeStart',[],...  % date and time started
            'DateTimeEnd',[]);    	% date and time ended

    case TYPE_CAP
        StructType = struct(...	% initialize structure
            'Channel',[],...    % channel name
            'Voltage',[],...    % voltage bias
            'Current',[],...    % leakage curent
            'StepData',[],...
            'Resistance',[],...
            'Regression',[],...
            'Capacitance',[],...
            'DateTimeStart',[],...  % date and time started
            'DateTimeEnd',[]);    	% date and time ended

    case TYPE_STEP
        StructType = struct(...	% initialize structure
            'Channel',[],...    % channel name
            'Time',[],...       % time
            'Voltage',[],...    % voltage bias
            'Current',[],...    % leakage curent
            'Failure',Failure,...
            'DateTimeStart',[],...  % date and time started
            'DateTimeEnd',[]);    	% date and time ended
end
fprintf('OK.\n');   % structure initialized

end